# Generated by Django 3.1 on 2024-08-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswerimage',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
