# Generated by Django 3.1 on 2024-08-09 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_studentanswerimage_answer_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='classroom.user')),
                ('semester', models.PositiveBigIntegerField(null=True)),
            ],
        ),
    ]
